using System.Text.RegularExpressions;

namespace Tests;

/// <summary>
/// Extracts half-line candidates for the banquet/drinking minigame's random poem-quote flavor
/// text. Root cause (confirmed via decompile, see Converter/output/_NoNamespace/DrinkUIController.cs
/// around DrinkUIController.DrinkPoemText's usage): when this quote list is picked, the game
/// itself does <c>char splitChar = '\uFF0C'; String.Split(line, splitChar)</c> and displays each
/// half as its OWN separate floating-text bubble (one over the player, one over the opponent) -
/// the full "raw，raw" line is NEVER shown as one string, so a whole-line-only dictionary entry
/// can never match at runtime; only the individually-displayed halves can. This is the same
/// shape of problem as PoetryDataWorkflow's "对诗" fill-in-the-blank halves, just for a different,
/// hardcoded (not JSON-loaded) source list.
///
/// The quote strings themselves are already correctly captured as whole-line entries by the
/// generic IL2CPP string-map scan ("3. ExtractIl2CppStringMapCandidates" -> dynamicStrings.txt),
/// since they're compiled string literals, not runtime JSON - so this workflow does NOT re-dump
/// them. It only adds the comma-split HALVES as additional bare candidates.
///
/// The DrinkPoemText list itself is read directly out of the decompiled
/// Converter/output/_NoNamespace/DrinkUIController.cs (regenerated by Converter, same as every
/// other decompile-derived source here) rather than hand-transcribed, so a future game patch that
/// adds/changes quotes is picked up automatically just by re-running Converter - no manual list
/// maintenance. Bounded by the DrinkTalkText/DrinkPoemText field-assignment markers in that
/// static constructor (see DrinkUIController's cctor) - field names are real IL2CPP metadata and
/// stable across decompiles, unlike the local variable names around them.
///
/// Writes into its OWN dedicated dynamicStringsDrinkQuotes.txt (see
/// GameFileHandling.TextFilesToSplit) - same DynamicStringsIL2CPP export/translate/package
/// plumbing as dynamicStrings.txt/dynamicStringsPoetry.txt. Idempotent.
/// </summary>
public static class DrinkQuoteWorkflow
{
    private static readonly Regex CjkPunctuationSplit = new(@"[，。？！；、]+", RegexOptions.Compiled);
    private static readonly Regex StringLiteralRegex = new("\"((?:[^\"\\\\]|\\\\.)*)\"", RegexOptions.Compiled);

    private const string StartMarker = "DrinkUIController.DrinkTalkText = ";
    private const string EndMarker = "DrinkUIController.DrinkPoemText = ";

    // Reads the DrinkPoemText string literals straight out of the decompiled DrinkUIController.cs
    // static constructor - see this file's doc comment for why the field-name markers (not the
    // local variable name assigned to them) are used as the bounds.
    private static List<string> ReadDrinkPoemTextFromDecompiledSource(string workingDirectory)
    {
        var path = Path.GetFullPath(Path.Combine(workingDirectory, "..", "Converter", "output", "_NoNamespace", "DrinkUIController.cs"));
        if (!File.Exists(path)) return [];

        var text = File.ReadAllText(path);
        var start = text.IndexOf(StartMarker, StringComparison.Ordinal);
        if (start < 0) return [];
        start += StartMarker.Length;

        var end = text.IndexOf(EndMarker, start, StringComparison.Ordinal);
        if (end < 0 || end <= start) return [];

        return StringLiteralRegex.Matches(text[start..end])
            .Select(m => m.Groups[1].Value)
            .Where(s => !string.IsNullOrWhiteSpace(s))
            .ToList();
    }

    public static void ExtractDrinkQuoteCandidates(string workingDirectory)
    {
        var poemLines = ReadDrinkPoemTextFromDecompiledSource(workingDirectory);
        if (poemLines.Count == 0) return;

        var outputPath = $"{workingDirectory}/Raw/Dumped/DynamicStrings/dynamicStringsDrinkQuotes.txt";
        var seen = GameFileHandling.GetExistingDynamicStringValues(outputPath);

        var found = new List<string>();

        foreach (var line in poemLines)
        {
            foreach (var half in CjkPunctuationSplit.Split(line))
            {
                if (string.IsNullOrWhiteSpace(half)) continue;
                if (!seen.Add(half)) continue;
                found.Add(half);
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.AppendAllLines(outputPath, found);
    }
}

