using Il2CppExplorer;
using Il2CppExplorer.Decompilers;
using Il2CppExplorer.Services;

Console.WriteLine("═══════════════════════════════════════════════════════");
Console.WriteLine("  Il2CppExplorer — IL2CPP dummy DLL → native C decompile");
Console.WriteLine("═══════════════════════════════════════════════════════");
Console.WriteLine();

// ── 1. Parse & validate config ────────────────────────────────────────────────
Config cfg;
try
{
    cfg = Config.Parse(args);
    cfg.Validate();
}
catch (Exception ex)
{
    Console.Error.WriteLine($"[ERROR] {ex.Message}");
    Console.Error.WriteLine("Run with --help for usage.");
    return 1;
}

if (!string.IsNullOrEmpty(cfg.GameDir))
    Console.WriteLine($"  GameDir : {cfg.GameDir}");
Console.WriteLine($"  DLL     : {cfg.DllPath}");
if (!cfg.SkipDecompile)
{
    Console.WriteLine($"  Binary  : {cfg.BinaryPath}");
    Console.WriteLine($"  Ghidra  : {cfg.GhidraInstallDir}");
}
if (!string.IsNullOrEmpty(cfg.MetadataPath))
    Console.WriteLine($"  Metadata: {cfg.MetadataPath}");
Console.WriteLine($"  Output  : {cfg.OutputDir}");
if (!string.IsNullOrEmpty(cfg.TypeFilter))
    Console.WriteLine($"  Filter  : {cfg.TypeFilter}");
Console.WriteLine(cfg.AllNamespaces
    ? "  Scope   : all namespaces"
    : "  Scope   : _NoNamespace only  (pass --all-namespaces to include libraries)");
Console.WriteLine();

// ── 1b. Diagnostic mode ──────────────────────────────────────────────────────
if (cfg.Diag)
{
    Console.WriteLine("[DIAG] Dumping raw custom attributes from DLL...");
    new DllParser().RunDiagnostic(cfg.DllPath);
    Console.Error.WriteLine($"[DIAG2] Binary='{cfg.BinaryPath}' Meta='{cfg.MetadataPath}' Ver='{cfg.UnityVersion}'");
    if (!string.IsNullOrEmpty(cfg.BinaryPath) && !string.IsNullOrEmpty(cfg.MetadataPath) && !string.IsNullOrEmpty(cfg.UnityVersion))
    {
        Console.Error.WriteLine("\n[DIAG] Checking LibCpp2IL binary API...");
        NativeMethodExtractor.ExtractMethodLabels(cfg.BinaryPath, cfg.MetadataPath, cfg.UnityVersion);
        NativeMethodExtractor.DumpBinaryApi();
    }
    return 0;
}

// ── 2. Parse dummy DLL ────────────────────────────────────────────────────────
Console.WriteLine("[1/4] Parsing dummy DLL...");
var parser = new DllParser();
var types = parser.Parse(cfg.DllPath, cfg.TypeFilter, noNamespaceOnly: !cfg.AllNamespaces);
Console.WriteLine();

if (types.Count == 0)
{
    Console.Error.WriteLine("[WARNING] No types found. Check --dll path and --filter.");
    return 1;
}

// ── 3. Assign output paths & write manifest CSV ──────────────────────────────
Console.WriteLine("[2/4] Writing manifest...");
var manifestWriter = new ManifestWriter();
string manifestPath = manifestWriter.Write(types, cfg.OutputDir, cfg.UseFileOffset);

// Write labels for ALL methods (unfiltered) — Ghidra uses these to rename FUN_ addresses
string? labelsPath = null;
if (!cfg.SkipDecompile)
{
    var allTypes = parser.ParseAll(cfg.DllPath);

    // If interop directories are provided, also parse every DLL there (Unity engine +
    // framework stubs generated by Cpp2IL/BepInEx) and add their methods to the labels.
    foreach (string interopDir in cfg.InteropDirs.Where(Directory.Exists))
    {
        int interopMethods = 0;
        foreach (var dll in Directory.GetFiles(interopDir, "*.dll", SearchOption.TopDirectoryOnly))
        {
            // Skip the game's own Assembly-CSharp — already parsed above
            string name = Path.GetFileNameWithoutExtension(dll);
            if (name.Equals("Assembly-CSharp", StringComparison.OrdinalIgnoreCase)) continue;
            try
            {
                var interopTypes = parser.ParseAll(dll);
                int withAddr = interopTypes.Sum(t => t.Members.Count(m => m.Address != null));
                if (withAddr > 0)
                {
                    allTypes.AddRange(interopTypes);
                    interopMethods += withAddr;
                }
            }
            catch { /* skip unreadable DLLs silently */ }
        }
        Console.WriteLine($"  Interop  : +{interopMethods} methods from {interopDir}");
    }

    // Optional: use LibCpp2IL to extract native method labels for ALL types (game + engine)
    Dictionary<string, string>? nativeLabels = null;
    if (cfg.NativeLabels)
    {
        if (string.IsNullOrEmpty(cfg.UnityVersion))
            Console.WriteLine("  [NativeLabels] --native-labels requires --unity-version (e.g. 2020.3.48f1). Skipping.");
        else
            nativeLabels = NativeMethodExtractor.ExtractMethodLabels(
                cfg.BinaryPath, cfg.MetadataPath, cfg.UnityVersion);
    }

    labelsPath = manifestWriter.WriteLabels(allTypes, cfg.OutputDir, cfg.UseFileOffset, nativeLabels);
    Console.WriteLine($"  Labels   : {allTypes.Sum(t => t.Members.Count(m => m.Address != null))} methods for Ghidra renaming");
}
Console.WriteLine();

int withAddresses = types.Sum(t => t.Members.Count(m => m.Address != null));
Console.WriteLine($"  Methods with native addresses : {withAddresses}");

if (withAddresses == 0)
{
    Console.WriteLine("[WARNING] No methods with [Cpp2ILInjected.Address] found.");
    Console.WriteLine("          Check that the DLL was produced by Cpp2IL with address injection enabled.");
}

// ── 4. Decompile with Ghidra ─────────────────────────────────────────────────
if (!cfg.SkipDecompile && withAddresses > 0)
{
    Console.WriteLine("[3/4] Decompiling with Ghidra headless...");
    Console.WriteLine($"      This may take a while for large binaries.");
    Console.WriteLine();

    // Copy the Ghidra script next to the project dir so -scriptPath resolves it
    string scriptDir = Path.Combine(AppContext.BaseDirectory, "Scripts");
    if (!Directory.Exists(scriptDir))
    {
        // Fallback: look relative to the exe (for published/self-contained builds)
        scriptDir = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)!, "Scripts");
    }

    if (!File.Exists(Path.Combine(scriptDir, "GhidraDecompile.java")))
    {
        Console.Error.WriteLine($"[ERROR] GhidraDecompile.java not found in: {scriptDir}");
        Console.Error.WriteLine("        Ensure the Scripts/ folder is next to the executable.");
        return 1;
    }

    var decompiler = new GhidraDecompiler(
        ghidraInstallDir: cfg.GhidraInstallDir,
        projectDir: cfg.GhidraProjectDir,
        projectName: cfg.GhidraProjectName,
        binaryPath: cfg.BinaryPath,
        scriptDir: scriptDir,
        timeoutSeconds: cfg.DecompileTimeoutSeconds,
        labelsPath: labelsPath,
        staticLabelsPath: File.Exists(Path.Combine(cfg.OutputDir, "_static_labels.csv"))
            ? Path.Combine(cfg.OutputDir, "_static_labels.csv")
            : null
    );

    using var cts = new CancellationTokenSource();
    Console.CancelKeyPress += (_, e) => { e.Cancel = true; cts.Cancel(); };

    try
    {
        await decompiler.DecompileAsync(manifestPath, cts.Token);
    }
    catch (OperationCanceledException)
    {
        Console.WriteLine("\n  Cancelled by user.");
        return 130;
    }
}
else if (cfg.SkipDecompile)
{
    Console.WriteLine("[3/4] Skipped decompilation (--skip-decompile).");
}

Console.WriteLine();

// ── 5. Resolve string literals from global-metadata.dat ──────────────────────
Console.WriteLine("[4/5] Resolving IL2CPP string literals...");
var stringMap = new Dictionary<string, string>();

string? effectiveMetadata = cfg.MetadataPath;
if (string.IsNullOrEmpty(effectiveMetadata))
    effectiveMetadata = null;

if (effectiveMetadata != null && !string.IsNullOrEmpty(cfg.BinaryPath))
{
    string mapCsv = Path.Combine(cfg.OutputDir, "_string_map.csv");
    if (File.Exists(mapCsv) && !cfg.SkipDecompile == false)
    {
        // Re-use cached map when skipping decompile
        Console.WriteLine($"  Loading existing string map from cache...");
        stringMap = StringMapExtractor.LoadCsv(mapCsv);
        Console.WriteLine($"  Loaded {stringMap.Count} entries.");
    }
    else
    {
        stringMap = StringMapExtractor.ExtractAndSave(effectiveMetadata, cfg.BinaryPath, cfg.OutputDir);
    }
}
else if (effectiveMetadata == null)
{
    Console.WriteLine("  No global-metadata.dat found.  Pass --metadata <path> to enable string resolution.");
}
Console.WriteLine();

// ── 6. Write per-class .cs files ─────────────────────────────────────────────
Console.WriteLine("[5/5] Writing class files...");

// allTypesForRegistry: all parsed types for building cross-class offset registries.
// When --filter is active this will be set to the full parse; otherwise stays null
// and WriteAll falls back to the filtered 'types' list (which is already everything).
List<Il2CppExplorer.Models.TypeInfo>? allTypesForRegistry = null;

// If we have native field offsets from LibCpp2IL (loaded either in step 3 via
// --native-labels, or from a standalone load here), patch TypeInfo.FieldOffsets
// and StaticFieldOffsets with the real IL2CPP values instead of our computed ones.
// This requires the binary + metadata + unity version to be available.
if (!string.IsNullOrEmpty(cfg.BinaryPath) && !string.IsNullOrEmpty(cfg.MetadataPath)
    && !string.IsNullOrEmpty(cfg.UnityVersion))
{
    // LibCpp2IL may already be loaded (from --native-labels above); ExtractFieldOffsets
    // checks if Binary is null and loads if needed. We load it fresh only for skip-decompile.
    if (cfg.SkipDecompile && LibCpp2IL.LibCpp2IlMain.Binary == null)
    {
        Console.Write("  [FieldOffsets] Loading IL2CPP metadata for field offset extraction...");
        try
        {
            var ver = AssetRipper.Primitives.UnityVersion.Parse(cfg.UnityVersion);
            LibCpp2IL.LibCpp2IlMain.LoadFromFile(cfg.BinaryPath, cfg.MetadataPath, ver);
            Console.WriteLine(" done.");
        }
        catch (Exception ex) { Console.WriteLine($" failed: {ex.Message}"); }
    }

    if (LibCpp2IL.LibCpp2IlMain.Binary != null)
    {
        var nativeFieldOffsets = NativeMethodExtractor.ExtractFieldOffsets();
        // Patch types with accurate native offsets (split instance vs static by sign convention:
        // LibCpp2IL returns negative offsets for static fields).
        // When --filter is active, parse all types so cross-class offset lookups work.
        allTypesForRegistry = string.IsNullOrEmpty(cfg.TypeFilter) ? null : parser.ParseAll(cfg.DllPath);
        foreach (var t in (allTypesForRegistry ?? types))
        {
            if (!nativeFieldOffsets.TryGetValue(t.ClassName, out var allOffsets)) continue;
            var inst = new Dictionary<string, int>(StringComparer.Ordinal);
            var stat = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var kv in allOffsets)
            {
                if (kv.Value < 0)
                    stat[kv.Key] = -(kv.Value) - 1; // decode -(offset+1) encoding back to offset
                else
                    inst[kv.Key] = kv.Value;
            }
            if (inst.Count > 0) t.FieldOffsets = inst;
            if (stat.Count > 0) t.StaticFieldOffsets = stat;
        }
    }
}

// Load previous-run _static_labels.csv to resolve DAT_XXXX addresses → class names.
// Enables passes 3d/3e/3f to handle **(int64**)(DAT_XXXX + 0xb8) singleton access chains.
var datToClass = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
{
    string staticLabCsv = Path.Combine(cfg.OutputDir, "_static_labels.csv");
    if (File.Exists(staticLabCsv))
    {
        foreach (var csvLine in File.ReadAllLines(staticLabCsv).Skip(1))
        {
            var parts = csvLine.Split(',');
            if (parts.Length < 2) continue;
            string addr = parts[0].Trim();
            if (addr.StartsWith("0x", StringComparison.OrdinalIgnoreCase)) addr = addr[2..];
            string label = parts[1].Trim();
            if (label.EndsWith("_StaticsPtr", StringComparison.OrdinalIgnoreCase))
                label = label[..^"_StaticsPtr".Length];
            datToClass[addr.ToLowerInvariant()] = label;
        }
        Console.WriteLine($"  [StaticLabels] Loaded {datToClass.Count} DAT_→class mappings.");
    }
}
var summaryWriter = new SummaryWriter(stringMap);
summaryWriter.WriteAll(types, allTypesForRegistry, datToClass);

// Write _static_labels.csv so Ghidra labels class statics-pointer addresses on the next run
summaryWriter.WriteStaticLabels(cfg.OutputDir);

// Clean up temp _decompiled folder (only when --clean-decompile is passed)
string decompDir = Path.Combine(cfg.OutputDir, "_decompiled");
if (!cfg.KeepDecompiled && Directory.Exists(decompDir))
{
    Directory.Delete(decompDir, recursive: true);
    Console.WriteLine("  Cleaned up temp decompiled files.");
}
else if (cfg.KeepDecompiled && Directory.Exists(decompDir))
{
    Console.WriteLine($"  Kept decompiled intermediates in: {decompDir}");
}
Console.WriteLine();

// ── Done ──────────────────────────────────────────────────────────────────────
Console.WriteLine("═══════════════════════════════════════════════════════");
Console.WriteLine($"  Done!  Output: {Path.GetFullPath(cfg.OutputDir)}");
Console.WriteLine("═══════════════════════════════════════════════════════");
Console.WriteLine();
Console.WriteLine("  Output structure:");
Console.WriteLine("    <output>/");
Console.WriteLine("      _manifest.csv          ← all addresses");
Console.WriteLine("      _string_map.csv        ← DAT_ address → string value");
Console.WriteLine("      <Namespace>/");
Console.WriteLine("        <ClassName>.cs        ← one file per class with full decompiled C inline");

return 0;
