models:
  - name: Qwen25-Standard
    modelPreset: Qwen25 
    modelPresetType: Standard
    customPromptsPath: 
    apiKeyPath: 
  - name: Qwen25-StructuredText
    modelPreset:  Qwen25
    modelPresetType: StructuredText
    customPromptsPath: 
    apiKeyPath: 
glossaryPreset:
  usePresetChineseGlossary: true
  chineseGlossaryTypesToSupress:
    - Phonetics
useContinuousWorkerPool: true
retryCount: 1
batchSize: 100
skipLineValidation: false
correctionPromptsEnabled: true
translateFlagged: true
extraStringTokenReplacers:
  - '#PlayerName#'
splitCharactersList:
  # - '\n'
  # - '<br>'
  # - '⑩'
  # - '⓪'
  # - '①'
  # - '②'
  # - '③'
  # - '④'
  # - '⑤'
  # - '⑥'
  # - '⑦'
  # - '⑧'
  # - '⑨'
  # - '-' # This will split between other groups
  # - ':' # This will split between other groups
  # - '|'
  # - '。'
  # - '-' 
splitRegexPatterns:
  #- '(.*?)',
  #- '（.*?）',
  # - '《.*?》'
  # - '\〈.*?\〉'
  # - '\「.*?\」'
  # - '\『.*?\』'
  # - '\【.*?\】'
  # - '\〖.*?\〗'
  # - '\“.*?”'